patchlevel_event_sourcing_admin_default_index:
  path: /
  controller: Patchlevel\EventSourcingAdminBundle\Controller\DefaultController::indexAction

patchlevel_event_sourcing_admin_default_dashboard:
  path: /dashboard
  controller: Patchlevel\EventSourcingAdminBundle\Controller\DefaultController::dashboardAction

patchlevel_event_sourcing_admin_store_show:
  path: /store
  controller: Patchlevel\EventSourcingAdminBundle\Controller\StoreController::showAction

patchlevel_event_sourcing_admin_subscription_show:
  path: /subscription
  controller: Patchlevel\EventSourcingAdminBundle\Controller\SubscriptionController::showAction

patchlevel_eventsourcingadmin_subscription_rebuild:
  path: /subscription/{id}/rebuild
  controller: Patchlevel\EventSourcingAdminBundle\Controller\SubscriptionController::rebuildAction

patchlevel_eventsourcingadmin_subscription_pause:
  path: /subscription/{id}/pause
  controller: Patchlevel\EventSourcingAdminBundle\Controller\SubscriptionController::pauseAction

patchlevel_eventsourcingadmin_subscription_setup:
  path: /subscription/{id}/setup
  controller: Patchlevel\EventSourcingAdminBundle\Controller\SubscriptionController::setupAction

patchlevel_eventsourcingadmin_subscription_reactivate:
  path: /subscription/{id}/reactivate
  controller: Patchlevel\EventSourcingAdminBundle\Controller\SubscriptionController::reactivateAction

patchlevel_eventsourcingadmin_subscription_remove:
  path: /subscription/{id}/remove
  controller: Patchlevel\EventSourcingAdminBundle\Controller\SubscriptionController::removeAction

patchlevel_event_sourcing_admin_inspection_index:
  path: /inspection
  controller: Patchlevel\EventSourcingAdminBundle\Controller\InspectionController::indexAction

patchlevel_event_sourcing_admin_inspection_show:
  path: /inspection/{aggregateName}/{aggregateId}
  controller: Patchlevel\EventSourcingAdminBundle\Controller\InspectionController::showAction

patchlevel_event_sourcing_admin_event_index:
  path: /event
  controller: Patchlevel\EventSourcingAdminBundle\Controller\EventController::indexAction

patchlevel_event_sourcing_admin_graph_index:
  path: /graph
  controller: Patchlevel\EventSourcingAdminBundle\Controller\GraphController::indexAction
