patchlevel_event_sourcing_admin_default_index:
  path: /
  controller: Patchlevel\EventSourcingAdminBundle\Controller\DefaultController::indexAction

patchlevel_event_sourcing_admin_default_dashboard:
  path: /dashboard
  controller: Patchlevel\EventSourcingAdminBundle\Controller\DefaultController::dashboardAction

patchlevel_event_sourcing_admin_store_show:
  path: /store
  controller: Patchlevel\EventSourcingAdminBundle\Controller\StoreController::showAction

patchlevel_event_sourcing_admin_projection_show:
  path: /projection
  controller: Patchlevel\EventSourcingAdminBundle\Controller\ProjectionController::showAction

patchlevel_eventsourcingadmin_projection_rebuild:
  path: /projection/{id}/rebuild
  controller: Patchlevel\EventSourcingAdminBundle\Controller\ProjectionController::rebuildAction

patchlevel_eventsourcingadmin_projection_pause:
  path: /projection/{id}/pause
  controller: Patchlevel\EventSourcingAdminBundle\Controller\ProjectionController::pauseAction

patchlevel_eventsourcingadmin_projection_reactivate:
  path: /projection/{id}/reactivate
  controller: Patchlevel\EventSourcingAdminBundle\Controller\ProjectionController::reactivateAction

patchlevel_eventsourcingadmin_projection_remove:
  path: /projection/{id}/remove
  controller: Patchlevel\EventSourcingAdminBundle\Controller\ProjectionController::removeAction

patchlevel_event_sourcing_admin_inspection_index:
  path: /inspection
  controller: Patchlevel\EventSourcingAdminBundle\Controller\InspectionController::indexAction

patchlevel_event_sourcing_admin_inspection_show:
  path: /inspection/{aggregateName}/{aggregateId}
  controller: Patchlevel\EventSourcingAdminBundle\Controller\InspectionController::showAction

patchlevel_event_sourcing_admin_event_index:
  path: /event
  controller: Patchlevel\EventSourcingAdminBundle\Controller\EventController::indexAction
